server.port=8090

spring.jpa.showSql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=com.codingapi.example.dialect.HydDmDialect

spring.datasource.url=jdbc:dm://localhost:5236
spring.datasource.username=SYSDBA
spring.datasource.password=SYSDBA001
spring.datasource.driverClassName=dm.jdbc.driver.DmDriver

# Security
spring.main.allow-bean-definition-overriding=true
codingapi.security.jwt.enable=true

codingapi.security.ignore-urls=/open/**,/#/**,/,/**.css,/**.js,/**.svg,/**.png,/**.ico
